export const data = [
  {
    src: "https://hips.hearstapps.com/hmg-prod/images/ghk090123goodstuff-001-655c0f419de10.jpg?crop=1xw:1xh;center,top&resize=980:*",
    name: "EcoCraft Creations",
    service: "Handmade Home Decor",
    rating: "4.9",
    address: "123 Recycle Lane, Delhi",
  },
  {
    src: "https://images.squarespace-cdn.com/content/v1/58e51576ebbd1a0eb2660515/1665982890118-Y1LEAP8UFX8AB04XXXIN/IMG_7958.jpg?format=1000w",
    name: "Green Upcycled Goods",
    service: "Upcycled Furniture",
    rating: "4.8",
    address: "456 Eco Ave, Green Town",
  },
  {
    src: "https://www.goingzerowaste.com/wp-content/uploads/2020/04/img_5e753b474bb5f.jpg",
    name: "Leftover Gourmet",
    service: "Handmade Snacks from Leftover Food",
    rating: "4.8",
    address: "808  Street, Flavor Town",
  },
  {
    src: "https://theinspiredclassroom.com/wp-content/uploads/2013/07/recyclebuttons.png",
    name: "Reclaimed Artistry",
    service: "Recycled Art Pieces",
    rating: "4.7",
    address: "789 Art Street, Creative City",
  },
  {
    src: "https://teacherbakermaker.com/wp-content/uploads/elementor/thumbs/Halloween-bottle-craft-haunted-house-py9iqqzcqshziwd8m237s3gyblehzkkpfiojok6kmw.jpg",
    name: "Bottle & Glass Studio",
    service: "Glass and Bottle Crafts",
    rating: "4.6",
    address: "101 Craft Blvd, Eco Village",
  },
  {
    src: "https://images.jdmagicbox.com/comp/jaipur/b8/0141px141.x141.110327154645.x1b8/catalogue/marudhara-handmade-paper-and-handicrafts-tonk-road-jaipur-paper-bag-manufacturers-6y5cg1zcg0-250.jpg",
    name: "Paper Pioneers",
    service: "Handmade Paper Products",
    rating: "4.5",
    address: "202 Paper Lane, Green City",
  },
  {
    src: "https://wellfabric.com/wp-content/uploads/2023/11/Making-a-Tote-Bag-from-fabric-scrap-recycling.jpg",
    name: "Fabric Forward",
    service: "Recycled Fabric Goods",
    rating: "4.7",
    address: "303 Fabric Rd, Sustainable City",
  },
  {
    src: "https://images1.novica.net/pictures/27/p455593_1.jpg",
    name: "Woven Wonders",
    service: "Handcrafted Baskets",
    rating: "4.4",
    address: "404 Weave St, Craft Town",
  },
  {
    src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa3Skr5M3VgxAfdn38bDqwy8xSSKKf6kPbNA&s",
    name: "Metal Marvels",
    service: "Upcycled Metal Sculptures",
    rating: "4.8",
    address: "505 Metal Way, Artisan Village",
  },
  {
    src: "https://i.ytimg.com/vi/zvB0AcPKRAM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBAWwncIv1dY3Q_TSnu-fmSLTFIYA",
    name: "Eco-Friendly Jewelry",
    service: "Handmade Jewelry from Recycled Materials",
    rating: "4.6",
    address: "606 Jewelry St, Eco District",
  },
  {
    src: "https://craftprojectideas.com/wp-content/uploads/2016/11/recycled-monsters-1442-recycled_monsters_mn.jpg",
    name: "Upcycled Toys",
    service: "Handcrafted Toys from Waste Materials",
    rating: "4.5",
    address: "707 Toy Rd, Playful City",
  },
  {
    src: "https://aucourant-interiors.com/cdn/shop/products/large_1_1642356412.jpg?v=1655475278",
    name: "Candle Creations",
    service: "Eco-Friendly Recycled Candles",
    rating: "4.8",
    address: "1010 Candle Blvd, Glow City",
  }
];
